import type { CollectionAfterChangeHook } from 'payload'
import { calculateCommissions } from '../utils/referral/calculateCommissions'

export const paymentAfterChange: CollectionAfterChangeHook = async ({
  doc,
  previousDoc,
  req,
  operation,
}) => {
  const { payload } = req

  const newStatus: string = doc.status
  const oldStatus: string | undefined = previousDoc?.status

  // Only sync when status changes or on create
  if (operation === 'update' && oldStatus === newStatus) return doc

  const orderId = typeof doc.order === 'object' ? doc.order.id : doc.order
  if (!orderId) return doc

  // Transition from non-paid → paid: create delta commission if the order
  // already had commissions generated by a previous payment (top-up flow).
  const becamePaid = newStatus === 'paid' && oldStatus !== 'paid'

  try {
    // Map payment status to order payment status
    const paymentUpdate: Record<string, any> = {
      'payment.status': newStatus,
    }

    if (doc.method) {
      paymentUpdate['payment.method'] = doc.method === 'gateway'
        ? (doc.gateway || 'yokassa')
        : doc.method
    }

    if (doc.transactionId) {
      paymentUpdate['payment.transactionId'] = doc.transactionId
    }

    if (newStatus === 'paid' && doc.paidAt) {
      paymentUpdate['payment.paidAt'] = doc.paidAt
    } else if (newStatus === 'paid' && !doc.paidAt) {
      paymentUpdate['payment.paidAt'] = new Date().toISOString()
      // Also update the payment record itself
      await payload.update({
        collection: 'payments',
        id: doc.id,
        data: { paidAt: new Date().toISOString() },
        req,
      })
    }

    await payload.update({
      collection: 'orders',
      id: orderId,
      data: paymentUpdate,
      req,
    })

    // If paid, move order from 'new' to 'processing'
    if (newStatus === 'paid') {
      const order = await payload.findByID({
        collection: 'orders',
        id: orderId,
        depth: 0,
        req,
      })
      if (order && order.status === 'new') {
        await payload.update({
          collection: 'orders',
          id: orderId,
          data: { status: 'processing' },
          req,
        })
      }

      // --- Top-up delta commission ---
      // If this payment is a top-up to an order that already has commissions,
      // generate an additional commission row on the delta amount.
      if (becamePaid) {
        await handleTopUpDeltaCommission(payload, orderId, doc, req)
      }
    }
  } catch (err) {
    console.error(`[paymentAfterChange] Error syncing payment to order ${orderId}:`, err)
  }

  return doc
}

/**
 * When a new payment on an existing order gets paid and that order already had
 * referral commissions created for it (i.e. the first payment triggered them),
 * emit a single `referral_repeat` commission for this payment's amount so the
 * partner gets their cut of the top-up too.
 */
async function handleTopUpDeltaCommission(
  payload: any,
  orderId: string | number,
  paymentDoc: any,
  req: any,
): Promise<void> {
  try {
    const order = await payload.findByID({
      collection: 'orders',
      id: orderId,
      depth: 0,
      req,
    })
    if (!order) return
    if (!order.referralCommissionsCreated) return // first payment flow will handle base commissions
    if (!order.referralPartner) return

    const paymentAmount = Number(paymentDoc.amount || 0)
    if (paymentAmount <= 0) return

    // Guard: commission with triggeringPayment=this payment already exists?
    const existing = await payload.find({
      collection: 'commissions' as any,
      where: { triggeringPayment: { equals: paymentDoc.id } },
      limit: 1,
      req,
    })
    if (existing.docs.length > 0) return

    const settings = (await payload.findGlobal({ slug: 'referral-settings' as any })) as any
    if (!settings?.enabled) return

    const partnerId = typeof order.referralPartner === 'object'
      ? order.referralPartner.id
      : order.referralPartner
    const partner = (await payload.findByID({
      collection: 'referral-partners' as any,
      id: partnerId,
      req,
    })) as any
    if (!partner || partner.status !== 'active') return

    // Build a "synthetic order" whose total equals the delta, so that the
    // existing commission calculator gives us a row scaled to the top-up.
    const syntheticOrder = {
      ...order,
      id: order.id,
      total: paymentAmount,
      createdAt: paymentDoc.paidAt || paymentDoc.createdAt || new Date().toISOString(),
    }
    const buyerId = typeof order.customer === 'object' ? order.customer.id : order.customer

    const commissions = await calculateCommissions({
      payload,
      order: syntheticOrder,
      buyerId,
      partner,
      isFirstPurchase: false, // top-up is always a repeat by definition
      settings,
    })

    const balanceIncrementByPartner = new Map<string | number, number>()
    for (const c of commissions) {
      try {
        await payload.create({
          collection: 'commissions' as any,
          data: {
            ...c,
            triggeringPayment: paymentDoc.id,
            notes: `Докомплектация заказа ${order.orderNumber}: +${paymentAmount}₽`,
          } as any,
          req,
        })
        const prev = balanceIncrementByPartner.get(c.recipient) || 0
        balanceIncrementByPartner.set(c.recipient, prev + c.amount)
      } catch (err) {
        console.error('[paymentAfterChange/topup] failed to create delta commission:', err)
      }
    }

    for (const [recipientId, amount] of balanceIncrementByPartner.entries()) {
      try {
        const p = (await payload.findByID({
          collection: 'referral-partners' as any,
          id: recipientId,
          req,
        })) as any
        await payload.update({
          collection: 'referral-partners' as any,
          id: recipientId,
          data: {
            balance: Number(p?.balance || 0) + amount,
            totalEarned: Number(p?.totalEarned || 0) + amount,
          } as any,
          req,
        })
      } catch (err) {
        console.error('[paymentAfterChange/topup] failed to update partner balance:', err)
      }
    }
  } catch (err) {
    console.error('[paymentAfterChange/topup] fatal:', err)
  }
}
