/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    customers: CustomerAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    products: Product;
    categories: Category;
    orders: Order;
    customers: Customer;
    posts: Post;
    'promo-codes': PromoCode;
    deliveries: Delivery;
    payments: Payment;
    recipes: Recipe;
    warehouses: Warehouse;
    'stock-movements': StockMovement;
    'stock-levels': StockLevel;
    inventories: Inventory;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'promo-codes': PromoCodesSelect<false> | PromoCodesSelect<true>;
    deliveries: DeliveriesSelect<false> | DeliveriesSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    recipes: RecipesSelect<false> | RecipesSelect<true>;
    warehouses: WarehousesSelect<false> | WarehousesSelect<true>;
    'stock-movements': StockMovementsSelect<false> | StockMovementsSelect<true>;
    'stock-levels': StockLevelsSelect<false> | StockLevelsSelect<true>;
    inventories: InventoriesSelect<false> | InventoriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'ai-settings': AiSetting;
    'delivery-settings': DeliverySetting;
    'landing-settings': LandingSetting;
    'shop-settings': ShopSetting;
  };
  globalsSelect: {
    'ai-settings': AiSettingsSelect<false> | AiSettingsSelect<true>;
    'delivery-settings': DeliverySettingsSelect<false> | DeliverySettingsSelect<true>;
    'landing-settings': LandingSettingsSelect<false> | LandingSettingsSelect<true>;
    'shop-settings': ShopSettingsSelect<false> | ShopSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Customer;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Администратор — полный доступ. Менеджер — заказы, клиенты, каталог. Кладовщик — склад. Контент — статьи, рецепты, лендинг.
   */
  role?: ('admin' | 'manager' | 'warehouse' | 'content') | null;
  active?: boolean | null;
  phone?: string | null;
  position?: string | null;
  inviteToken?: string | null;
  inviteExpires?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    full?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  slug: string;
  shortDescription?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  price: number;
  oldPrice?: number | null;
  sku?: string | null;
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  category?: (number | null) | Category;
  variants?:
    | {
        name: string;
        price: number;
        sku?: string | null;
        id?: string | null;
      }[]
    | null;
  composition?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  usage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  weight?: number | null;
  /**
   * Набор автоматически раскладывается на базовые товары при списании
   */
  isBundle?: boolean | null;
  /**
   * Базовые товары, из которых состоит набор
   */
  bundleItems?:
    | {
        product: number | Product;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  inStock?: boolean | null;
  featured?: boolean | null;
  status?: ('active' | 'hidden' | 'archived') | null;
  amoCrmId?: number | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  icon?: (number | null) | Media;
  parent?: (number | null) | Category;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber: string;
  customer: number | Customer;
  items: {
    product: number | Product;
    variantName?: string | null;
    quantity: number;
    /**
     * Заполняется автоматически из товара/варианта
     */
    price: number;
    id?: string | null;
  }[];
  /**
   * Считается автоматически
   */
  subtotal?: number | null;
  discount?: number | null;
  deliveryCost?: number | null;
  /**
   * Считается автоматически: сумма товаров − скидка + доставка
   */
  total: number;
  status?: ('new' | 'processing' | 'shipped' | 'delivered' | 'completed' | 'cancelled') | null;
  payment?: {
    method?: ('yokassa' | 'tinkoff' | 'cash') | null;
    transactionId?: string | null;
    status?: ('pending' | 'paid' | 'cancelled' | 'refunded') | null;
    paidAt?: string | null;
  };
  delivery?: {
    method?: ('cdek' | 'russian_post' | 'pickup') | null;
    address?: string | null;
    trackingNumber?: string | null;
  };
  /**
   * Создаётся автоматически при создании заказа
   */
  linkedDelivery?: (number | null) | Delivery;
  /**
   * Создаётся автоматически при создании заказа
   */
  linkedPayment?: (number | null) | Payment;
  promoCode?: (number | null) | PromoCode;
  source?: ('site' | 'telegram_bot' | 'import') | null;
  /**
   * Внутренний ID заказа из PuzzleBot
   */
  puzzleBotOrderId?: string | null;
  importedAt?: string | null;
  amoCrmDealId?: number | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  name?: string | null;
  phone?: string | null;
  avatar?: (number | null) | Media;
  addresses?:
    | {
        title?: string | null;
        city?: string | null;
        street?: string | null;
        apartment?: string | null;
        zip?: string | null;
        id?: string | null;
      }[]
    | null;
  role?: ('customer' | 'vip' | 'blocked') | null;
  amoCrmContactId?: number | null;
  bonusBalance?: number | null;
  favorites?: (number | Product)[] | null;
  /**
   * Данные из Telegram (заполняются автоматически при авторизации или импорте)
   */
  telegram?: {
    chatId?: string | null;
    username?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    phone?: string | null;
    photoUrl?: string | null;
  };
  source?: ('site' | 'telegram_bot' | 'import' | 'amocrm') | null;
  /**
   * Внутренний ID пользователя из PuzzleBot
   */
  puzzleBotId?: string | null;
  importedAt?: string | null;
  emailVerified?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'customers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deliveries".
 */
export interface Delivery {
  id: number;
  order: number | Order;
  method: 'pickup' | 'cdek' | 'russian_post';
  status?: ('pending' | 'handed_over' | 'in_transit' | 'arrived_at_pickup' | 'delivered' | 'returned') | null;
  /**
   * Трек-номер СДЭК или почтовый идентификатор
   */
  trackingNumber?: string | null;
  cdekOrderUuid?: string | null;
  recipient: {
    name: string;
    phone: string;
    email?: string | null;
  };
  address?: {
    city?: string | null;
    street?: string | null;
    apartment?: string | null;
    zip?: string | null;
  };
  pickupPoint?: {
    code?: string | null;
    name?: string | null;
    address?: string | null;
  };
  weight?: number | null;
  cost?: number | null;
  estimatedDeliveryDate?: string | null;
  deliveredAt?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  order: number | Order;
  method: 'gateway' | 'cash' | 'card_transfer' | 'invoice';
  gateway?: ('none' | 'yokassa' | 'tinkoff' | 'cloudpayments') | null;
  status?: ('pending' | 'paid' | 'failed' | 'cancelled' | 'refunded') | null;
  amount: number;
  /**
   * Внешний идентификатор платежа от шлюза
   */
  transactionId?: string | null;
  /**
   * Raw JSON ответ от платёжного шлюза
   */
  gatewayResponse?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  paidAt?: string | null;
  refundedAt?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promo-codes".
 */
export interface PromoCode {
  id: number;
  code: string;
  discountType: 'percent' | 'fixed';
  discountValue: number;
  minOrderAmount?: number | null;
  maxUses?: number | null;
  usedCount?: number | null;
  validFrom?: string | null;
  validTo?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  coverImage?: (number | null) | Media;
  category?: string | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  author?: string | null;
  publishedAt?: string | null;
  status?: ('draft' | 'published') | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recipes".
 */
export interface Recipe {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  coverImage?: (number | null) | Media;
  difficulty?: ('easy' | 'medium' | 'hard') | null;
  prepTime?: number | null;
  /**
   * Например: 3-5 дней, 2 недели
   */
  fermentationTime?: string | null;
  servings?: number | null;
  ingredients?:
    | {
        name: string;
        /**
         * Например: 500 мл, 2 ст.л., 1 пакет
         */
        amount?: string | null;
        optional?: boolean | null;
        id?: string | null;
      }[]
    | null;
  steps?:
    | {
        step: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        image?: (number | null) | Media;
        tip?: string | null;
        id?: string | null;
      }[]
    | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Закваски и другие продукты ЭТРА для этого рецепта
   */
  relatedProducts?: (number | Product)[] | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  status?: ('draft' | 'published') | null;
  publishedAt?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "warehouses".
 */
export interface Warehouse {
  id: number;
  /**
   * Например: Склад производства, Склад СДЭК
   */
  name: string;
  type: 'production' | 'logistics' | 'retail';
  /**
   * Сотрудник, ответственный за склад
   */
  responsible?: (number | null) | User;
  address?: string | null;
  active?: boolean | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Журнал всех операций: производство, перемещение, отправка, списание
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-movements".
 */
export interface StockMovement {
  id: number;
  operationType:
    | 'produced'
    | 'sent_to_logistics'
    | 'received_at_logistics'
    | 'shipped_to_customers'
    | 'retail_shipment'
    | 'employee_issue'
    | 'write_off'
    | 'return_to_stock'
    | 'inventory_adjustment';
  /**
   * Товары и количество для этой операции. Наборы раскладываются автоматически.
   */
  items: {
    product: number | Product;
    quantity: number;
    id?: string | null;
  }[];
  /**
   * Склад, на котором выполняется операция
   */
  warehouse: number | Warehouse;
  /**
   * Только для перемещений — куда отправляется товар
   */
  targetWarehouse?: (number | null) | Warehouse;
  status?: ('completed' | 'in_transit' | 'cancelled') | null;
  operator?: (number | null) | User;
  /**
   * Если операция связана с конкретным заказом
   */
  order?: (number | null) | Order;
  /**
   * Если товар был автоматически разложен из набора
   */
  bundle?: (number | null) | Product;
  /**
   * Например: Гранат, ярмарка и т.д.
   */
  retailPoint?: string | null;
  employeeName?: string | null;
  /**
   * Причина списания, примечание к операции
   */
  reason?: string | null;
  date: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Текущие остатки товаров по складам
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-levels".
 */
export interface StockLevel {
  id: number;
  product: number | Product;
  warehouse: number | Warehouse;
  /**
   * Автоматически рассчитывается из журнала движений
   */
  calculated: number;
  /**
   * Заполняется вручную при инвентаризации
   */
  actual?: number | null;
  /**
   * Товар, зарезервированный под заказы
   */
  reserved?: number | null;
  /**
   * Товар в пути между складами
   */
  inTransit?: number | null;
  /**
   * calculated - reserved - inTransit
   */
  available?: number | null;
  lastInventoryDate?: string | null;
  /**
   * actual - calculated (заполняется при инвентаризации)
   */
  discrepancy?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Фиксация фактических остатков и расхождений
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventories".
 */
export interface Inventory {
  id: number;
  warehouse: number | Warehouse;
  date: string;
  status?: ('draft' | 'in_progress' | 'completed' | 'cancelled') | null;
  conductor?: (number | null) | User;
  items: {
    product: number | Product;
    /**
     * Из системы на момент инвентаризации
     */
    calculatedQty: number;
    /**
     * Посчитанное количество
     */
    actualQty: number;
    /**
     * actual - calculated
     */
    discrepancy?: number | null;
    note?: string | null;
    id?: string | null;
  }[];
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'promo-codes';
        value: number | PromoCode;
      } | null)
    | ({
        relationTo: 'deliveries';
        value: number | Delivery;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'recipes';
        value: number | Recipe;
      } | null)
    | ({
        relationTo: 'warehouses';
        value: number | Warehouse;
      } | null)
    | ({
        relationTo: 'stock-movements';
        value: number | StockMovement;
      } | null)
    | ({
        relationTo: 'stock-levels';
        value: number | StockLevel;
      } | null)
    | ({
        relationTo: 'inventories';
        value: number | Inventory;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  active?: T;
  phone?: T;
  position?: T;
  inviteToken?: T;
  inviteExpires?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        full?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  description?: T;
  price?: T;
  oldPrice?: T;
  sku?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  category?: T;
  variants?:
    | T
    | {
        name?: T;
        price?: T;
        sku?: T;
        id?: T;
      };
  composition?: T;
  usage?: T;
  weight?: T;
  isBundle?: T;
  bundleItems?:
    | T
    | {
        product?: T;
        quantity?: T;
        id?: T;
      };
  inStock?: T;
  featured?: T;
  status?: T;
  amoCrmId?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  icon?: T;
  parent?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  customer?: T;
  items?:
    | T
    | {
        product?: T;
        variantName?: T;
        quantity?: T;
        price?: T;
        id?: T;
      };
  subtotal?: T;
  discount?: T;
  deliveryCost?: T;
  total?: T;
  status?: T;
  payment?:
    | T
    | {
        method?: T;
        transactionId?: T;
        status?: T;
        paidAt?: T;
      };
  delivery?:
    | T
    | {
        method?: T;
        address?: T;
        trackingNumber?: T;
      };
  linkedDelivery?: T;
  linkedPayment?: T;
  promoCode?: T;
  source?: T;
  puzzleBotOrderId?: T;
  importedAt?: T;
  amoCrmDealId?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  avatar?: T;
  addresses?:
    | T
    | {
        title?: T;
        city?: T;
        street?: T;
        apartment?: T;
        zip?: T;
        id?: T;
      };
  role?: T;
  amoCrmContactId?: T;
  bonusBalance?: T;
  favorites?: T;
  telegram?:
    | T
    | {
        chatId?: T;
        username?: T;
        firstName?: T;
        lastName?: T;
        phone?: T;
        photoUrl?: T;
      };
  source?: T;
  puzzleBotId?: T;
  importedAt?: T;
  emailVerified?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  coverImage?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  author?: T;
  publishedAt?: T;
  status?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promo-codes_select".
 */
export interface PromoCodesSelect<T extends boolean = true> {
  code?: T;
  discountType?: T;
  discountValue?: T;
  minOrderAmount?: T;
  maxUses?: T;
  usedCount?: T;
  validFrom?: T;
  validTo?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deliveries_select".
 */
export interface DeliveriesSelect<T extends boolean = true> {
  order?: T;
  method?: T;
  status?: T;
  trackingNumber?: T;
  cdekOrderUuid?: T;
  recipient?:
    | T
    | {
        name?: T;
        phone?: T;
        email?: T;
      };
  address?:
    | T
    | {
        city?: T;
        street?: T;
        apartment?: T;
        zip?: T;
      };
  pickupPoint?:
    | T
    | {
        code?: T;
        name?: T;
        address?: T;
      };
  weight?: T;
  cost?: T;
  estimatedDeliveryDate?: T;
  deliveredAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  order?: T;
  method?: T;
  gateway?: T;
  status?: T;
  amount?: T;
  transactionId?: T;
  gatewayResponse?: T;
  paidAt?: T;
  refundedAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recipes_select".
 */
export interface RecipesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  coverImage?: T;
  difficulty?: T;
  prepTime?: T;
  fermentationTime?: T;
  servings?: T;
  ingredients?:
    | T
    | {
        name?: T;
        amount?: T;
        optional?: T;
        id?: T;
      };
  steps?:
    | T
    | {
        step?: T;
        image?: T;
        tip?: T;
        id?: T;
      };
  content?: T;
  relatedProducts?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  status?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "warehouses_select".
 */
export interface WarehousesSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  responsible?: T;
  address?: T;
  active?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-movements_select".
 */
export interface StockMovementsSelect<T extends boolean = true> {
  operationType?: T;
  items?:
    | T
    | {
        product?: T;
        quantity?: T;
        id?: T;
      };
  warehouse?: T;
  targetWarehouse?: T;
  status?: T;
  operator?: T;
  order?: T;
  bundle?: T;
  retailPoint?: T;
  employeeName?: T;
  reason?: T;
  date?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-levels_select".
 */
export interface StockLevelsSelect<T extends boolean = true> {
  product?: T;
  warehouse?: T;
  calculated?: T;
  actual?: T;
  reserved?: T;
  inTransit?: T;
  available?: T;
  lastInventoryDate?: T;
  discrepancy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventories_select".
 */
export interface InventoriesSelect<T extends boolean = true> {
  warehouse?: T;
  date?: T;
  status?: T;
  conductor?: T;
  items?:
    | T
    | {
        product?: T;
        calculatedQty?: T;
        actualQty?: T;
        discrepancy?: T;
        note?: T;
        id?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-settings".
 */
export interface AiSetting {
  id: number;
  /**
   * URL API-эндпоинта (совместимого с OpenRouter/OpenAI)
   */
  aiApiUrl?: string | null;
  /**
   * Секретный ключ для доступа к API
   */
  aiApiKey?: string | null;
  /**
   * Модель для генерации текстов (описания товаров, статьи, SEO)
   */
  aiTextModel?:
    | (
        | 'openai/gpt-4.1-mini'
        | 'openai/gpt-4.1'
        | 'openai/gpt-4o'
        | 'openai/gpt-4o-mini'
        | 'anthropic/claude-3.5-sonnet'
        | 'anthropic/claude-3.5-haiku'
        | 'google/gemini-2.0-flash'
        | 'google/gemini-2.5-pro'
        | 'deepseek/deepseek-chat-v3'
        | 'meta-llama/llama-3.1-70b-instruct'
      )
    | null;
  /**
   * Модель для генерации и редактирования изображений
   */
  aiImageModel?:
    | (
        | 'google/gemini-3-pro-image-preview'
        | 'google/gemini-3.1-flash-image-preview'
        | 'google/gemini-2.5-flash-image'
        | 'openai/gpt-5-image'
        | 'openai/gpt-5-image-mini'
        | 'openai/gpt-image-1.5'
        | 'bytedance/seedream-5-lite'
        | 'bytedance/seedream-4.5'
        | 'black-forest-labs/flux.2-pro'
        | 'black-forest-labs/flux.2-flex'
        | 'x-ai/grok-imagine-image'
        | 'topaz/image-upscale'
      )
    | null;
  /**
   * Креативность генерации (0 = точно, 2 = максимально креативно)
   */
  aiTemperature?: number | null;
  /**
   * Максимальная длина ответа в токенах
   */
  aiMaxTokens?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "delivery-settings".
 */
export interface DeliverySetting {
  id: number;
  deliveryPickupEnabled?: boolean | null;
  deliveryPickupAddress?: string | null;
  cdekEnabled?: boolean | null;
  /**
   * Идентификатор клиента из ЛК СДЭК
   */
  cdekAccount?: string | null;
  /**
   * Секретный ключ из ЛК СДЭК
   */
  cdekSecurePassword?: string | null;
  cdekTestMode?: boolean | null;
  /**
   * Код города в системе СДЭК (44 = Москва)
   */
  cdekSenderCity?: string | null;
  /**
   * 139 = посылка дверь-ПВЗ, 138 = посылка дверь-дверь
   */
  cdekTariffCode?: number | null;
  cdekSenderName?: string | null;
  /**
   * Формат: +79991234567
   */
  cdekSenderPhone?: string | null;
  /**
   * Улица, дом — для забора курьером
   */
  cdekSenderAddress?: string | null;
  /**
   * Вес товара если не указан в карточке
   */
  cdekDefaultWeight?: number | null;
  /**
   * Автоматически: /api/cdek/webhook. Зарегистрируйте в ЛК СДЭК или через API.
   */
  cdekWebhookUrl?: string | null;
  russianPostEnabled?: boolean | null;
  /**
   * Токен API Почты России (otpravka.pochta.ru)
   */
  russianPostToken?: string | null;
  russianPostLogin?: string | null;
  russianPostPassword?: string | null;
  /**
   * Почтовый индекс точки отправки
   */
  russianPostSenderIndex?: string | null;
  /**
   * Собственные точки самовывоза
   */
  pickupPoints?:
    | {
        name: string;
        address: string;
        city?: string | null;
        phone?: string | null;
        /**
         * Например: Пн-Пт 10:00-20:00, Сб 10:00-18:00
         */
        workingHours?: string | null;
        lat?: number | null;
        lng?: number | null;
        active?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-settings".
 */
export interface LandingSetting {
  id: number;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  heroCta?: string | null;
  heroCtaLink?: string | null;
  heroSecondaryCtaText?: string | null;
  heroSecondaryCtaLink?: string | null;
  /**
   * Если не задано, используется /images/hero-bg.jpg
   */
  heroBgImage?: (number | null) | Media;
  stats?:
    | {
        number: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  scienceLabel?: string | null;
  scienceTitle?: string | null;
  scienceDesc?: string | null;
  scienceImage?: (number | null) | Media;
  scienceFeatures?:
    | {
        icon?: string | null;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  catalogLabel?: string | null;
  catalogTitle?: string | null;
  catalogDesc?: string | null;
  /**
   * Если включено, отображаются товары с галочкой «На главной»
   */
  catalogShowFeatured?: boolean | null;
  catalogMaxItems?: number | null;
  processLabel?: string | null;
  processTitle?: string | null;
  processDesc?: string | null;
  processSteps?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  testimonialsLabel?: string | null;
  testimonialsTitle?: string | null;
  testimonials?:
    | {
        text: string;
        name: string;
        role?: string | null;
        avatar?: (number | null) | Media;
        rating?: number | null;
        id?: string | null;
      }[]
    | null;
  joinTitle?: string | null;
  joinDesc?: string | null;
  joinButtonText?: string | null;
  footerDesc?: string | null;
  footerEmail?: string | null;
  footerPhone?: string | null;
  socialLinks?:
    | {
        platform: 'telegram' | 'vk' | 'instagram' | 'youtube' | 'whatsapp';
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-settings".
 */
export interface ShopSetting {
  id: number;
  /**
   * Токен бота из @BotFather для авторизации клиентов через Telegram Login Widget
   */
  telegramBotToken?: string | null;
  /**
   * Имя бота для Telegram Login Widget, например: etra_auth_bot
   */
  telegramBotUsername?: string | null;
  paymentEnabled?: boolean | null;
  paymentProvider?: ('yokassa' | 'tinkoff') | null;
  paymentApiKey?: string | null;
  paymentShopId?: string | null;
  minOrderAmount?: number | null;
  /**
   * 0 = бесплатная доставка отключена
   */
  freeDeliveryThreshold?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-settings_select".
 */
export interface AiSettingsSelect<T extends boolean = true> {
  aiApiUrl?: T;
  aiApiKey?: T;
  aiTextModel?: T;
  aiImageModel?: T;
  aiTemperature?: T;
  aiMaxTokens?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "delivery-settings_select".
 */
export interface DeliverySettingsSelect<T extends boolean = true> {
  deliveryPickupEnabled?: T;
  deliveryPickupAddress?: T;
  cdekEnabled?: T;
  cdekAccount?: T;
  cdekSecurePassword?: T;
  cdekTestMode?: T;
  cdekSenderCity?: T;
  cdekTariffCode?: T;
  cdekSenderName?: T;
  cdekSenderPhone?: T;
  cdekSenderAddress?: T;
  cdekDefaultWeight?: T;
  cdekWebhookUrl?: T;
  russianPostEnabled?: T;
  russianPostToken?: T;
  russianPostLogin?: T;
  russianPostPassword?: T;
  russianPostSenderIndex?: T;
  pickupPoints?:
    | T
    | {
        name?: T;
        address?: T;
        city?: T;
        phone?: T;
        workingHours?: T;
        lat?: T;
        lng?: T;
        active?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-settings_select".
 */
export interface LandingSettingsSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  heroCta?: T;
  heroCtaLink?: T;
  heroSecondaryCtaText?: T;
  heroSecondaryCtaLink?: T;
  heroBgImage?: T;
  stats?:
    | T
    | {
        number?: T;
        label?: T;
        id?: T;
      };
  scienceLabel?: T;
  scienceTitle?: T;
  scienceDesc?: T;
  scienceImage?: T;
  scienceFeatures?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  catalogLabel?: T;
  catalogTitle?: T;
  catalogDesc?: T;
  catalogShowFeatured?: T;
  catalogMaxItems?: T;
  processLabel?: T;
  processTitle?: T;
  processDesc?: T;
  processSteps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  testimonialsLabel?: T;
  testimonialsTitle?: T;
  testimonials?:
    | T
    | {
        text?: T;
        name?: T;
        role?: T;
        avatar?: T;
        rating?: T;
        id?: T;
      };
  joinTitle?: T;
  joinDesc?: T;
  joinButtonText?: T;
  footerDesc?: T;
  footerEmail?: T;
  footerPhone?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-settings_select".
 */
export interface ShopSettingsSelect<T extends boolean = true> {
  telegramBotToken?: T;
  telegramBotUsername?: T;
  paymentEnabled?: T;
  paymentProvider?: T;
  paymentApiKey?: T;
  paymentShopId?: T;
  minOrderAmount?: T;
  freeDeliveryThreshold?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}